### PR TITLE
Make CNI resilient to an already existing route

### LINKED ISSUE #352: Error setting up networking: error adding host side routes for interface: xxx, error: failed to add route file exists
If old route exists, set up networking will fail. This may happen in situation describe here: #275 

Some log here:

```
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Extracted identifiers" Node=kube-node-52 Orchestrator=k8s Workload=infra.console-web-2894439173-nk9cj
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Loaded CNI NetConf" NetConfg={ k8s-pod-network calico { host-local usePodCidr <nil> <nil> [] []} 0  kube-node-52 kubernetes   info {k8s  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VNlYWNjb3VudC9zydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXpveThxIiwia3ViZXJuZXRlcy5pby9zZXJ2aWZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrMDBkOTg3YmdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJlNWRlZTJhNi1kZmYwLTExZTYtOGQwNS01MjU0QiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.l3aHAY1WNj_rS-lZ4sM6O6ssJBuELLBb-xFi2jVzeWleAeFBbgo9KX0SQ_KglcI58XDNVopNzSqaequdbIck0tubinvtksBL0D_tMT7C_kRcSxf_3k3MyVwLr3TKilNW94Hs-6ani7ox2Iwo2AUUthGzI48zo_qMufMVy48qiN1fFpGGfCwRbl5Ax4aXaEQUDTxL8-34EpHwFUdiPB626YLWzTaUWWqFqbXC3DQJMimWLIMXmSE5Bt1siOBxTv1RqQlJ1RowAwfZ9xvQOnRtj8lYhfP0bzJXQouMmxDFuNiCFM6_hyHeDo5tPXM6cpysIz7XuU521lNko0sEEAwHuA   } {https://10.254.0.1:443 /etc/cni/net.d/calico-kubeconfig } {{{ {[]}}}}    } Workload=infra.console-web-2894439173-nk9cj
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Configured environment: [LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin KUBE_LOGTOSTDERR=--logtostderr=true KUBE_LOG_LEVEL=--v=0 KUBE_ALLOW_PRIV=--allow-privileged=true KUBE_MASTER=--master=https://192.168.18.60:443 KUBE_CLOUD_PROVIDER= KUBELET_ADDRESS=--address=192.168.16.224 KUBELET_HOSTNAME=--hostname-override=kube-node-52 KUBELET_API_SERVER= KUBELET_ARGS=--require-kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --pod-manifest-path=/etc/kubernetes/manifests --pod-infra-container-image=cargo.caicloudprivatetest.com/caicloudgcr/google_containers_pause-amd64:3.0 --node-ip=192.168.16.224 --cluster-dns=10.254.0.100 --cluster-domain=cluster.local --network-plugin=cni --feature-gates=Accelerators=true CNI_COMMAND=ADD CNI_CONTAINERID=69cfce426f2d757adc2d8e4389b96829f3b8155c9e0c4f5cf4d2bd3c056b3334 CNI_NETNS=/proc/21837/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=infra;K8S_POD_NAME=console-web-2894439173-nk9cj;K8S_POD_INFRA_CONTAINER_ID=69cfce426f2d757adc2d8e4389b96829f3b8155c9e0c4f5cf4d2bd3c056b3334 CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin DATASTORE_TYPE=kubernetes KUBECONFIG=/etc/cni/net.d/calico-kubeconfig K8S_API_ENDPOINT=https://10.254.0.1:443 K8S_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXpveThxIiwiaZXRlcy5pby9zZXJ2aWNl3ViZXJuYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bNlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJlNWRlZTJhNi1kZmYwLTExZTYtOGQwNS01MjU0MDBkOTg3YmQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZSHQiLCJrdWJlcm5ldGVzLmlvL31zeXN0ZW06ZGVmYXVsdCJ9.l3aHAY1WNj_rS-lZ4sM6O6ssJBuELLBb-xFi2jVzeWleAeFBbgo9KX0SQ_Kg4aXaEQUlcI58XDNVopNzSqaequdbIck0tubinvtksBL0D_tMT7C_kRcSxf_3k3MyVwLr3TKilNW94Hs-6ani7ox2Iwo2AUUthGzI48zo_qMufMVy48qiN1fFpGGfCwRbl5AxDTxL8-34EpHwFUdiPB626YLWzTaUWWqFqbXC3DQJMimWLIM
Jul 11 20:20:37 c8v224 kubelet[11183]: XmSE5Bt1siOBxTv1RqQlJ1RowAwfZ9xvQOnP0bzJXQouMmxDFuNiCFRtj8lYhfM6_hyHeDo5tPXM6cpysIz7XuU521lNko0sEEAwHuA]"
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Loading config from environment"
Jul 11 20:20:37 c8v224 kubelet[11183]: Calico CNI checking for existing endpoint: <nil>
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Extracted identifiers for CmdAddK8s" Node=kube-node-52 Orchestrator=k8s Workload=infra.console-web-2894439173-nk9cj
Jul 11 20:20:37 c8v224 kubelet[11183]: Calico CNI fetching podCidr from Kubernetes
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Fetched podCidr" Workload=infra.console-web-2894439173-nk9cj podCidr="10.100.2.0/24"
Jul 11 20:20:37 c8v224 kubelet[11183]: Calico CNI passing podCidr to host-local IPAM: 10.100.2.0/24
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Populated endpoint" Workload=infra.console-web-2894439173-nk9cj endpoint=&{{workloadEndpoint v1} {{<nil>} eth0 infra.console-web-2894439173-nk9cj k8s kube-node-52 69cfce426f2d757adc2d8e4389b96829f3b8155c9e0c4f5cf4d2bd3c056b3334 map[kubernetes-admin.caicloud.io/application:console-web kubernetes-admin.caicloud.io/select-by:service_infra_console-web kubernetes-admin.caicloud.io/type:application pod-template-hash:2894439173 calico/k8s_ns:infra]} {[10.100.2.42/32] [] <nil> <nil> [k8s_ns.infra]  <nil>}}
Jul 11 20:20:37 c8v224 kubelet[11183]: Calico CNI using IPs: [10.100.2.42/32]
Jul 11 20:20:37 c8v224 kubelet[11183]: I0711 20:20:37.253621   11183 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/840b78b1-e1dd-11e6-b4ef-525400d987bd-default-token-zoy8q" (spec.Name: "default-token-zoy8q") pod "840b78b1-e1dd-11e6-b4ef-525400d987bd" (UID: "840b78b1-e1dd-11e6-b4ef-525400d987bd").
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=error msg="Error setting up networking: error adding host side routes for interface: cali5ad046dac08, error: failed to add route file exists" Workload=infra.console-web-2894439173-nk9cj
Jul 11 20:20:37 c8v224 kubelet[11183]: time="2017-07-11T20:20:37+08:00" level=info msg="Cleaning up IP allocations for failed ADD" Workload=infra.console-web-2894439173-nk9cj
Jul 11 20:20:37 c8v224 kubelet[11183]: E0711 20:20:37.312002   11183 cni.go:257] Error adding network: error adding host side routes for interface: cali5ad046dac08, error: failed to add route file exists
Jul 11 20:20:37 c8v224 kubelet[11183]: E0711 20:20:37.312049   11183 cni.go:211] Error while adding to cni network: error adding host side routes for interface: cali5ad046dac08, error: failed to add route file exists
```

code here (https://github.com/projectcalico/cni-plugin/blob/master/utils/network.go#L170) may check err is not `route file exists`

```
	// Now that the host side of the veth is moved, state set to UP, and configured with sysctls, we can add the routes to it in the host namespace.
	err = setupRoutes(hostVeth, result)
	if err != nil {
		return "", "", fmt.Errorf("error adding host side routes for interface: %s, error: %s", hostVeth.Attrs().Name, err)
	}
```

### PR DESCRIPTION
**Pull request by gunjan5**
## Description
Fixes #352
CNI fails to setup network for the container/pod if the route already exists.

## Todos
- [x] Tests
- [x] Release note

## Release Note
```release-note
Fix for a bug where CNI network setup fails if the route already existed on the host.
```

### CODE REVIEW

File: utils/network.go [hunk 1]
```diff
@@ -182,9 +184,18 @@ func setupRoutes(hostVeth netlink.Link, result *current.Result) error {
...
 				Dst:       &ip.Address,
-			})
+			},
+		)
+
 		if err != nil {
-			return fmt.Errorf("failed to add route %v", err)
+			switch err {
+			case errFileExists:
+				// Route was already present on the host.
```
Comment (caseydavenport) [inline utils/network.go]: I can imagine this going a few ways, namely:
- We ignore and assume the route is correct, OR
- We take a look and re-program if it's not the right route.

Should probably understand what are the scenarios where we'll get "route exists" errors.  I'm assuming it's just when a route to the exact `w.x.y.z/32` exists?

Do we hit this when running alongside say, another plugin that thinks it owns that IP address?

**Comment by bradbehle** [comment]
What is the status on this PR?  We are hitting the problem documented in https://github.com/projectcalico/cni-plugin/issues/352 as well, and are looking for a fix.

**Comment by gmcquillan** [comment]
Likewise, we're hitting an issue with pod initialization daily due to IP conflicts on the container address. Might we cut an alpha or RC for this so folks might test in their staging environments?

File: utils/network.go [hunk 2]
```diff
@@ -174,20 +181,53 @@ func DoNetworking(args *skel.CmdArgs, conf NetConf, result *current.Result, logg
 	return hostVethName, contVethMAC, err
 }
 
+var errFileExists = fmt.Errorf("file exists")
```
Comment (caseydavenport) [inline utils/network.go]: :(

I guess this is the most robust way we can check this right now?

File: utils/network.go [hunk 3]
```diff
@@ -174,20 +181,53 @@ func DoNetworking(args *skel.CmdArgs, conf NetConf, result *current.Result, logg
...
+			Dst:       &ipAddr.Address,
+		}
 		err := netlink.RouteAdd(
-			&netlink.Route{
-				LinkIndex: hostVeth.Attrs().Index,
-				Scope:     netlink.SCOPE_LINK,
-				Dst:       &ip.Address,
-			})
+			&route,
+		)
```
Comment (caseydavenport) [inline utils/network.go]: This can be squashed onto a single line now.

File: utils/network.go [hunk 4]
```diff
@@ -174,20 +181,53 @@ func DoNetworking(args *skel.CmdArgs, conf NetConf, result *current.Result, logg
...
+				// If the route we want is already there then most likely it's programmed by Felix, so we ignore it,
+				// and we return an error if none of the routes match the route we're trying to program.
+				for _, r := range routes {
+					if reflect.DeepEqual(r, route) {
+						// Route was already present on the host.
+						log.Infof("CNI skipping add route. Route already exists for %s\n", hostVeth.Attrs().Name)
+						return nil
+					}
+				}
+
```
Comment (caseydavenport) [inline utils/network.go]: extra newline!

File: utils/network.go [hunk 5]
```diff
@@ -174,20 +181,53 @@ func DoNetworking(args *skel.CmdArgs, conf NetConf, result *current.Result, logg
...
+				return fmt.Errorf("route (Dst: %s, Scope: %s) already exists for an interface other than '%s'", route.Dst.String(), route.Scope, hostVeth.Attrs().Name)
+
```
Comment (caseydavenport) [inline utils/network.go]: extra newline!

File: utils/network.go (hunk 2 above)
Comment (gunjan5) [reply utils/network.go]: yes, I checked if netlink library has any builtin error types for this, but it doesn't have any for this

File: utils/network.go [hunk 6]
```diff
@@ -81,15 +83,20 @@ func DoNetworking(args *skel.CmdArgs, conf NetConf, result *current.Result, logg
...
-					Dst:       gwNet}); err != nil {
-					return fmt.Errorf("failed to add route %v", err)
+				err := netlink.RouteAdd(
+					&netlink.Route{
+						LinkIndex: contVeth.Attrs().Index,
+						Scope:     netlink.SCOPE_LINK,
+						Dst:       gwNet,
+					},
+				)
+
```
[the remark this answers is not in the document]
Comment (gunjan5) [reply utils/network.go]: I don't see any extra newline here. Just one separating variable declaration and if block. I don't want to make the code too cluttered by getting rid of that

**Comment by gunjan5** [comment]
semaphore seems kinda broken so closing and reopening this PR
